version: "3.9"

services:
  database: 
    image: postgres
    container_name: notification_db
    restart: always
    ports: 
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres
    env_file:
      - .env
volumes:
  pgdata:
    driver: local